# Конфигурация для spring + (в перспективе) postgresql

version: '3.9'
services:
  app-ktor:
    image: ok-marketplace-app-ktor-jvm:0.0.1
    ports:
      - "8080"
    environment:
      DB_TYPE_PROD: "arcadedb"
      DB_GREMLIN_HOST: "arcadedb"
      DB_GREMLIN_USER: "root"
      DB_GREMLIN_PASS: "root_root"
      DB_GREMLIN_PORT: 8182
      # MKPLADS_LOGGER: "logback"
    depends_on:
      arcadedb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]

  arcadedb:
    image: "arcadedata/arcadedb:25.9.1"
      #    ports:
      #      - "2480:2480"
      #      - "2424:2424"
      #      - "8182:8182"
      #    volumes:
      #      - ./volumes/arcadedb:/home/arcadedb/databases
    # Здесь можно добавить доступные через gremlin графы и псевдонимы
    #      - ./volumes/arcadedb:/home/arcadedb/config/gremlin-server.groovy
    environment:
      JAVA_OPTS: >
        -Darcadedb.server.rootPassword=root_root
        -Darcadedb.server.plugins=GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 2480 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
